# Steb04b Transformations Version1: All Features

## Import packages

In [2]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer

In [3]:
filepath = '../data/train_test_split/scherzer/raw/'

infile1 = open(filepath + 'X_test_2019.pickle','rb')
X_test = pickle.load(infile1)
infile1.close()

infile2 = open(filepath + 'y_test_2019_all_types.pickle','rb')
y_test = pickle.load(infile2)
infile2.close()

infile2 = open(filepath + 'y_test_2019_2_cases.pickle','rb')
y_test_2c = pickle.load(infile2)
infile2.close()

infile2 = open(filepath + 'y_test_2019_3_cases.pickle','rb')
y_test_3c = pickle.load(infile2)
infile2.close()

In [4]:
X_test.columns

Index(['pitch_number', 'stand', 'outs_when_up', 'inning', 'opp_score',
       'nats_score', 'if_fielding_alignment', 'of_fielding_alignment',
       'nats_home1_away0', 'balls_strikes', 'all_runners', 'pitch_season',
       'pitch_game', 'pitch_bat_gm', 'total_pitches', 'abs', 'whiffs',
       'swings', 'takes', 'k', 'walk', 'single', 'double', 'triple', 'hr',
       'line_drive', 'ground_ball', 'fly_ball', 'popup', 'rbi', 'sac', 'ba',
       'slg', 'iso', 'babip'],
      dtype='object')

In [5]:
X_test

pitch_number stand  outs_when_up  inning  opp_score  nats_score  \
1352             2     L             0       6          1           2   
1654             1     L             1       4          0           1   
846              0     L             0       2          0           0   
1761             1     L             1       4          0           6   
152              1     R             1       3          1           0   
...            ...   ...           ...     ...        ...         ...   
1584             0     R             1       7          2           5   
2273             0     L             0       1          0           0   
1178             2     R             1       1          0           0   
1097             2     R             1       3          0           1   
1306             2     R             1       3          0           1   

     if_fielding_alignment of_fielding_alignment  nats_home1_away0  \
1352         Infield shift              Standard                 0   
1654         Infield shift              Standard                 1   
846               Standard              Standard                 0   
1761              Standard              Standard                 0   
152               Standard              Standard                 1   
...                    ...                   ...               ...   
1584              Standard              Standard                 1   
2273              Standard              Standard                 1   
1178              Standard              Standard                 1   
1097              Standard              Standard                 0   
1306              Standard             Strategic                 0   

     balls_strikes  ... line_drive  ground_ball  fly_ball  popup  rbi  sac  \
1352           1_1  ...         34           53        53      5    8    1   
1654           0_1  ...         31           39        58     22   24    2   
846            0_0  ...         27           35        32      7   10    1   
1761           1_0  ...         34           45        32      3   10    0   
152            0_1  ...          1            7         0      0    0    0   
...            ...  ...        ...          ...       ...    ...  ...  ...   
1584           0_0  ...         49           97        41      8   23    7   
2273           0_0  ...         98          157        86     22   42    0   
1178           1_1  ...          9           23         4      1    5    0   
1097           1_1  ...         34           62        24      4   24    0   
1306           0_2  ...          0           10         0      1    0    2   

            ba       slg       iso     babip  
1352  0.247423  0.365979  0.118557  0.312057  
1654  0.230392  0.573529  0.343137  0.213740  
846   0.229630  0.348148  0.118519  0.292929  
1761  0.295302  0.442953  0.147651  0.363636  
152   0.250000  0.333333  0.083333  0.375000  
...        ...       ...       ...       ...  
1584  0.266667  0.404167  0.137500  0.314136  
2273  0.322430  0.523364  0.200935  0.349711  
1178  0.196078  0.313725  0.117647  0.228571  
1097  0.263158  0.403509  0.140351  0.341667  
1306  0.133333  0.133333  0.000000  0.181818  

[831 rows x 35 columns]

## Define Categorical Variables

In [6]:
cats = ['stand', 'if_fielding_alignment', 'of_fielding_alignment', 'balls_strikes', 'all_runners']

## Define Features that are already standardized

In [7]:
formatted = ['nats_home1_away0', 'ba', 'slg', 'iso', 'babip']

## Define MinMax Numeric Variables

In [8]:
minmax = ['outs_when_up', 'inning']

## Define StandardScaler Numeric Variables

In [9]:
standard = []
non_nums = cats + standard + minmax

for c in X_test.columns:
    if c not in non_nums:
        standard.append(c)

## Fit OHE

In [10]:
ohe = OneHotEncoder(drop='first', handle_unknown='error', sparse=False)

In [11]:
X_ohe_ar = ohe.fit_transform(X_test[cats])

In [12]:
ohe_cols = ['stand_r1', 'if_standard', 'if_strategic', 'of_strategic', 
        '0_1', '0_2', '1_0', '1_1', '1_2', '2_0', '2_1', '2_2', '3_0', '3_1', '3_2',
        'fb:0_sb:0_tb:1', 'fb:0_sb:1_tb:0', 'fb:0_sb:1_tb:1', 'fb:1_sb:0_tb:0', 
        'fb:1_sb:0_tb:1', 'fb:1_sb:1_tb:0', 'fb:1_sb:1_tb:1']

In [13]:
ohe_df = pd.DataFrame(data = X_ohe_ar, columns = ohe_cols).reset_index()

## Fit StandardScaler

In [14]:
ss = StandardScaler()

In [15]:
X_ss = ss.fit_transform(X_test[standard])

In [16]:
ss_df = pd.DataFrame(columns = standard, data = X_ss).reset_index()

## Fit MinMax Scaler

In [17]:
mm = MinMaxScaler()

In [18]:
X_mm = mm.fit_transform(X_test[minmax])

In [19]:
mm_df = pd.DataFrame(columns = minmax, data = X_mm).reset_index()

## Create DF for features that are already standardized

In [20]:
formatted_df = X_test[formatted].reset_index()

## Combine Processed X_test

In [21]:
ohe_df.shape, ss_df.shape, mm_df.shape, X_test[formatted].shape

((831, 23), (831, 29), (831, 3), (831, 5))

In [22]:
ohe_df.shape[1] + ss_df.shape[1] + mm_df.shape[1] + X_test[formatted].shape[1]

60

In [23]:
# X_test_trans = pd.DataFrame()
X_test_trans = pd.concat([mm_df, ss_df, ohe_df], axis = 1)
X_test_trans = X_test_trans.drop(columns = 'index')
X_test_trans

outs_when_up    inning  pitch_number  opp_score  nats_score  \
0             0.0  0.714286     -0.054563  -0.034680    0.226836   
1             0.5  0.428571     -0.607509  -0.882312   -0.273166   
2             0.0  0.142857     -1.160456  -0.882312   -0.773169   
3             0.5  0.428571     -0.607509  -0.882312    2.226846   
4             0.5  0.285714     -0.607509  -0.034680   -0.773169   
..            ...       ...           ...        ...         ...   
826           0.5  0.857143     -1.160456   0.812951    1.726844   
827           0.0  0.000000     -1.160456  -0.882312   -0.773169   
828           0.5  0.000000     -0.054563  -0.882312   -0.773169   
829           0.5  0.285714     -0.054563  -0.882312   -0.273166   
830           0.5  0.285714     -0.054563  -0.882312   -0.273166   

     nats_home1_away0  pitch_season  pitch_game  pitch_bat_gm  total_pitches  \
0           -1.048086     -0.022145    0.891496      1.007700       0.242557   
1            0.954120      0.354913    0.130955     -0.878864       0.203751   
2           -1.048086     -0.653903   -1.323994     -1.350506      -0.187292   
3           -1.048086      0.488506   -0.199715      0.064418      -0.103710   
4            0.954120     -1.520386   -0.298916     -0.643044      -1.012661   
..                ...           ...         ...           ...            ...   
826          0.954120      0.267515    1.255233     -0.171403       0.451511   
827          0.954120      1.127755   -1.720798     -1.350506       1.493297   
828          0.954120     -0.239390   -1.456262     -0.878864      -0.703707   
829         -1.048086     -0.340521   -0.530385      0.300238      -0.042516   
830         -1.048086     -0.079577   -0.629586     -0.878864      -0.982810   

     ...  3_0  3_1  3_2  fb:0_sb:0_tb:1  fb:0_sb:1_tb:0  fb:0_sb:1_tb:1  \
0    ...  0.0  0.0  0.0             0.0             0.0             0.0   
1    ...  0.0  0.0  0.0             0.0             0.0             0.0   
2    ...  0.0  0.0  0.0             0.0             0.0             0.0   
3    ...  0.0  0.0  0.0             0.0             1.0             0.0   
4    ...  0.0  0.0  0.0             0.0             0.0             0.0   
..   ...  ...  ...  ...             ...             ...             ...   
826  ...  0.0  0.0  0.0             0.0             0.0             0.0   
827  ...  0.0  0.0  0.0             0.0             0.0             0.0   
828  ...  0.0  0.0  0.0             0.0             0.0             0.0   
829  ...  0.0  0.0  0.0             0.0             0.0             0.0   
830  ...  0.0  0.0  0.0             0.0             0.0             0.0   

     fb:1_sb:0_tb:0  fb:1_sb:0_tb:1  fb:1_sb:1_tb:0  fb:1_sb:1_tb:1  
0               0.0             0.0             0.0             0.0  
1               0.0             0.0             0.0             0.0  
2               0.0             0.0             0.0             0.0  
3               0.0             0.0             0.0             0.0  
4               0.0             0.0             0.0             0.0  
..              ...             ...             ...             ...  
826             0.0             0.0             0.0             0.0  
827             0.0             0.0             0.0             0.0  
828             1.0             0.0             0.0             0.0  
829             0.0             0.0             0.0             0.0  
830             0.0             0.0             0.0             0.0  

[831 rows x 52 columns]

## Process y_test data

In [24]:
y_test.value_counts()
y_test = np.array(y_test).reshape(-1, 1)

In [25]:
o = OrdinalEncoder()
y_test_trans = o.fit_transform(y_test)
np.unique(y_test_trans)

array([0., 1., 2., 3., 4.])

## Process y_test_2c

In [26]:
y_test_2c = np.array(y_test_2c).reshape(-1, 1)

In [27]:
o2 = OrdinalEncoder()
y_test_2c = o2.fit_transform(y_test_2c)
np.unique(y_test_2c)

array([0., 1.])

## Proces y_test_3c

In [28]:
y_test_3c = np.array(y_test_3c).reshape(-1, 1)

In [29]:
o2 = OrdinalEncoder()
y_test_3c = o2.fit_transform(y_test_3c)
np.unique(y_test_3c)

array([0., 1., 2.])

## Export data

In [30]:
filepath = '../data/train_test_split/scherzer/transformed/'

pickle_out = open(filepath + 'X_test_2019_trans.pickle', 'wb')
pickle.dump(X_test_trans, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_test_2019_trans.pickle', 'wb')
pickle.dump(y_test_trans, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_test_2c_2019_trans.pickle', 'wb')
pickle.dump(y_test_2c, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_test_3c_2019_trans.pickle', 'wb')
pickle.dump(y_test_3c, pickle_out)
pickle_out.close()