# Steb04b Transformations Version1: All Features

## Import packages

In [10]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer

In [12]:
filepath = '../data/train_test_split/scherzer/raw/'

infile1 = open(filepath + 'X_train_2019.pickle','rb')
X_train = pickle.load(infile1)
infile1.close()

infile2 = open(filepath + 'y_train_2019_all_types.pickle','rb')
y_train = pickle.load(infile2)
infile2.close()

infile2 = open(filepath + 'y_train_2019_2_cases.pickle','rb')
y_train_2c = pickle.load(infile2)
infile2.close()

infile2 = open(filepath + 'y_train_2019_3_cases.pickle','rb')
y_train_3c = pickle.load(infile2)
infile2.close()

In [13]:
X_train.columns

Index(['pitch_number', 'stand', 'outs_when_up', 'inning', 'opp_score',
       'nats_score', 'if_fielding_alignment', 'of_fielding_alignment',
       'nats_home1_away0', 'balls_strikes', 'all_runners', 'pitch_season',
       'pitch_game', 'pitch_bat_gm', 'total_pitches', 'abs', 'whiffs',
       'swings', 'takes', 'k', 'walk', 'single', 'double', 'triple', 'hr',
       'line_drive', 'ground_ball', 'fly_ball', 'popup', 'rbi', 'sac', 'ba',
       'slg', 'iso', 'babip'],
      dtype='object')

In [14]:
X_train

pitch_number stand  outs_when_up  inning  opp_score  nats_score  \
576              1     R             0       6          1           2   
579              1     R             1       6          1           2   
2046             2     L             1       2          0           0   
1110             0     R             0       4          0           1   
500              0     R             1       6          4           3   
...            ...   ...           ...     ...        ...         ...   
1112             2     R             0       4          0           1   
2397             5     R             1       2          1           3   
30               0     L             1       3          1           0   
2602             1     L             2       3          1           0   
427              0     R             0       2          2           0   

     if_fielding_alignment of_fielding_alignment  nats_home1_away0  \
576               Standard              Standard                 1   
579               Standard             Strategic                 1   
2046              Standard              Standard                 1   
1110              Standard              Standard                 0   
500               Standard              Standard                 0   
...                    ...                   ...               ...   
1112              Standard              Standard                 0   
2397              Standard              Standard                 0   
30                Standard              Standard                 1   
2602         Infield shift              Standard                 0   
427               Standard              Standard                 0   

     balls_strikes  ... line_drive  ground_ball  fly_ball  popup  rbi  sac  \
576            0_1  ...         15           13        20      6    5    0   
579            0_1  ...          1            1         0      0    0    0   
2046           0_2  ...         58          103        45      5   23    0   
1110           0_0  ...         25           48        37      8   20    1   
500            0_0  ...         14           24        10      3    6    1   
...            ...  ...        ...          ...       ...    ...  ...  ...   
1112           2_0  ...         25           48        37      8   20    1   
2397           2_2  ...         92          122        92     17   46    6   
30             0_0  ...          0            0         0      0    0    0   
2602           0_1  ...         96          128        85     20   47    4   
427            0_0  ...          4            5         1      1    1    0   

            ba       slg       iso     babip  
576   0.268657  0.432836  0.164179  0.307692  
579   0.333333  0.500000  0.166667  1.000000  
2046  0.274021  0.451957  0.177936  0.343137  
1110  0.260355  0.603550  0.343195  0.274510  
500   0.301887  0.396226  0.094340  0.313725  
...        ...       ...       ...       ...  
1112  0.260355  0.603550  0.343195  0.274510  
2397  0.254197  0.443645  0.189448  0.290850  
30    0.000000  0.000000  0.000000  0.000000  
2602  0.247748  0.421171  0.173423  0.298077  
427   0.250000  0.250000  0.000000  0.272727  

[1939 rows x 35 columns]

## Define Categorical Variables

In [15]:
cats = ['stand', 'if_fielding_alignment', 'of_fielding_alignment', 'balls_strikes', 'all_runners']

## Define Features that are already standardized

In [16]:
formatted = ['nats_home1_away0', 'ba', 'slg', 'iso', 'babip']

## Define MinMax Numeric Variables

In [17]:
minmax = ['outs_when_up', 'inning']

## Define StandardScaler Numeric Variables

In [18]:
standard = []
non_nums = cats + standard + minmax

for c in X_train.columns:
    if c not in non_nums:
        standard.append(c)

## Fit OHE

In [19]:
ohe = OneHotEncoder(drop='first', handle_unknown='error', sparse=False)

In [20]:
X_ohe_ar = ohe.fit_transform(X_train[cats])

In [21]:
ohe_cols = ['stand_r1', 'if_standard', 'if_strategic', 'of_strategic', 
        '0_1', '0_2', '1_0', '1_1', '1_2', '2_0', '2_1', '2_2', '3_0', '3_1', '3_2',
        'fb:0_sb:0_tb:1', 'fb:0_sb:1_tb:0', 'fb:0_sb:1_tb:1', 'fb:1_sb:0_tb:0', 
        'fb:1_sb:0_tb:1', 'fb:1_sb:1_tb:0', 'fb:1_sb:1_tb:1']

In [22]:
ohe_df = pd.DataFrame(data = X_ohe_ar, columns = ohe_cols).reset_index()

## Fit StandardScaler

In [23]:
ss = StandardScaler()

In [24]:
X_ss = ss.fit_transform(X_train[standard])

In [25]:
ss_df = pd.DataFrame(columns = standard, data = X_ss).reset_index()

## Fit MinMax Scaler

In [26]:
mm = MinMaxScaler()

In [27]:
X_mm = mm.fit_transform(X_train[minmax])

In [28]:
mm_df = pd.DataFrame(columns = minmax, data = X_mm).reset_index()

## Create DF for features that are already standardized

In [29]:
formatted_df = X_train[formatted].reset_index()

## Combine Processed X_train

In [30]:
ohe_df.shape, ss_df.shape, mm_df.shape, X_train[formatted].shape

((1939, 23), (1939, 29), (1939, 3), (1939, 5))

In [31]:
ohe_df.shape[1] + ss_df.shape[1] + mm_df.shape[1] + X_train[formatted].shape[1]

60

In [32]:
# X_train_trans = pd.DataFrame()
X_train_trans = pd.concat([mm_df, ss_df, ohe_df], axis = 1)
X_train_trans = X_train_trans.drop(columns = 'index')
X_train_trans

outs_when_up    inning  pitch_number  opp_score  nats_score  \
0              0.0  0.714286     -0.508410  -0.011533    0.274116   
1              0.5  0.714286     -0.508410  -0.011533    0.274116   
2              0.5  0.142857      0.069437  -0.839770   -0.816163   
3              0.0  0.428571     -1.086257  -0.839770   -0.271023   
4              0.5  0.714286     -1.086257   2.473179    0.819255   
...            ...       ...           ...        ...         ...   
1934           0.0  0.428571      0.069437  -0.839770   -0.271023   
1935           0.5  0.142857      1.802978  -0.011533    0.819255   
1936           0.5  0.285714     -1.086257  -0.011533   -0.816163   
1937           1.0  0.285714     -0.508410  -0.011533   -0.816163   
1938           0.0  0.142857     -1.086257   0.816705   -0.816163   

      nats_home1_away0  pitch_season  pitch_game  pitch_bat_gm  total_pitches  \
0             0.889043     -1.019828    0.456515      0.125348      -0.735428   
1             0.889043     -1.016073    0.554614     -0.115057      -1.056135   
2             0.889043      0.820007   -1.047674     -0.836272       0.503862   
3            -1.124805     -0.351480   -0.066681     -0.115057       0.069966   
4            -1.124805     -1.114949    1.502907      0.365753      -0.816693   
...                ...           ...         ...           ...            ...   
1934         -1.124805     -0.348977   -0.001282      0.365753       0.069966   
1935         -1.124805      1.259314   -0.557178     -0.115057       1.656083   
1936          0.889043     -1.703195   -0.687977     -1.317082      -1.092414   
1937         -1.124805      1.515890   -0.295580      0.125348       2.069664   
1938         -1.124805     -1.206315   -0.884175     -1.317082      -1.035818   

      ...  3_0  3_1  3_2  fb:0_sb:0_tb:1  fb:0_sb:1_tb:0  fb:0_sb:1_tb:1  \
0     ...  0.0  0.0  0.0             0.0             0.0             0.0   
1     ...  0.0  0.0  0.0             0.0             0.0             0.0   
2     ...  0.0  0.0  0.0             0.0             0.0             0.0   
3     ...  0.0  0.0  0.0             0.0             0.0             0.0   
4     ...  0.0  0.0  0.0             0.0             0.0             0.0   
...   ...  ...  ...  ...             ...             ...             ...   
1934  ...  0.0  0.0  0.0             0.0             0.0             0.0   
1935  ...  0.0  0.0  0.0             0.0             0.0             0.0   
1936  ...  0.0  0.0  0.0             0.0             0.0             0.0   
1937  ...  0.0  0.0  0.0             0.0             0.0             0.0   
1938  ...  0.0  0.0  0.0             0.0             0.0             0.0   

      fb:1_sb:0_tb:0  fb:1_sb:0_tb:1  fb:1_sb:1_tb:0  fb:1_sb:1_tb:1  
0                0.0             0.0             0.0             0.0  
1                0.0             0.0             0.0             0.0  
2                0.0             0.0             0.0             0.0  
3                0.0             0.0             0.0             0.0  
4                0.0             0.0             0.0             0.0  
...              ...             ...             ...             ...  
1934             0.0             0.0             0.0             0.0  
1935             0.0             0.0             0.0             0.0  
1936             0.0             0.0             0.0             0.0  
1937             0.0             0.0             0.0             0.0  
1938             1.0             0.0             0.0             0.0  

[1939 rows x 52 columns]

## Process y_train data

In [33]:
y_train.value_counts()
y_train = np.array(y_train).reshape(-1, 1)

In [34]:
o = OrdinalEncoder()
y_train_trans = o.fit_transform(y_train)
np.unique(y_train_trans)

array([0., 1., 2., 3., 4.])

## Process y_train_2c

In [35]:
y_train_2c = np.array(y_train_2c).reshape(-1, 1)

In [36]:
o2 = OrdinalEncoder()
y_train_2c = o2.fit_transform(y_train_2c)
np.unique(y_train_2c)

array([0., 1.])

## Proces y_train_3c

In [37]:
y_train_3c = np.array(y_train_3c).reshape(-1, 1)

In [38]:
o2 = OrdinalEncoder()
y_train_3c = o2.fit_transform(y_train_3c)
np.unique(y_train_3c)

array([0., 1., 2.])

## Export data

In [39]:
filepath = '../data/train_test_split/scherzer/transformed/'

pickle_out = open(filepath + 'X_train_2019_trans.pickle', 'wb')
pickle.dump(X_train_trans, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_train_2019_trans.pickle', 'wb')
pickle.dump(y_train_trans, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_train_2c_2019_trans.pickle', 'wb')
pickle.dump(y_train_2c, pickle_out)
pickle_out.close()

pickle_out = open(filepath + 'y_train_3c_2019_trans.pickle', 'wb')
pickle.dump(y_train_3c, pickle_out)
pickle_out.close()